[tools]
"aqua:aquasecurity/kubectl-who-can" = "latest"
argo-rollouts                       = "latest"
argocd                              = "latest"
aws                                 = { symlink_bins = "true", version = "latest" }
bat                                 = "latest"
bun                                 = "latest"
cargo-binstall                      = "latest"
"cargo:sofka"                       = "latest"
chezmoi                             = "latest"
cocogitto                           = "latest"
crossplane-cli                      = "1"
delta                               = "latest"
direnv                              = "latest"
dyff                                = "latest"
fd                                  = "latest"
fzf                                 = "latest"
gcloud                              = "latest"
ghorg                               = "latest"
github-cli                          = "latest"
"github:armgabrielyan/deadbranch"   = "latest"
"github:bschaatsbergen/cidr"        = "latest"
"github:hatoo/oha"                  = "latest"
"github:imsnif/bandwhich"           = "latest"
glab                                = "latest"
go                                  = "latest"
"go:github.com/janosmiko/lfk"       = "latest"
"go:github.com/jrhouston/tfk8s"     = "latest"
helm                                = "latest"
k9s                                 = "latest"
kubectl                             = "latest"
kubectx                             = "latest"
lazygit                             = "latest"
node                                = "latest"
packer                              = "latest"
pre-commit                          = "latest"
prek                                = "latest"
python                              = "latest"
ripgrep                             = "latest"
ruby                                = "latest"
rust                                = "latest"
taplo                               = "latest"
terraform                           = "latest"
terragrunt                          = "latest"
tlrc                                = "latest"
typos                               = "latest"
usage                               = "latest"
uv                                  = "latest"
vault                               = "latest"
viddy                               = "latest"
yq                                  = "latest"

[settings]
minimum_release_age = "2h"
